from pathlib import Path
import os
import pandas as pd
from snakemake.utils import min_version

min_version("7.0")

wildcard_constraints:
	genomeset="\w+",
	k="\d+",
	prefix="[ACGT]+",


### Configuration ###
configfile: "config/config.yaml"

# Running in test mode?
TEST = config.get('test', False)
if TEST:
	print("Test mode enabled!")
	# Override default config file with values in test file
	configfile: "config/config-test.yaml"

os.environ["GAMBIT_DB_PATH"] = "resources/gambit-db"

K = config['gambit']['k']
PREFIX = config['gambit']['prefix']

# Main genome sets compared in figures 1 and 2
COMPARISON_GENOME_SETS = ['set1', 'set2', 'set3']


### Rules ###
include: "rules/src-data.smk"
include: "rules/fastani.smk"
include: "rules/gambit.smk"
include: "rules/figure-1.smk"
include: "rules/figure-2.smk"
include: "rules/figure-3.smk"
include: "rules/figure-6.smk"


rule all:
	input:
		*rules.figure_1.output,
		*rules.figure_2.output,
		*rules.figure_3.output,
		*rules.figure_6.output,


# Starts IPython shell with access to global scope of workflow. For testing/development.
rule debug:
	run:
		import IPython
		IPython.embed()
